nelmio_api_doc:
    documentation:
        info:
            title: PSU Publishing API
            description: This is the PSU Publishing API!
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api/v1
